### PR TITLE
Minor code fixes for warnings

### LINKED ISSUE #55: Camera follow is overloading DOTween

### PR DESCRIPTION
**Pull request by Horothenic**
Check the warning most of the time are helpful, DOTween was overloading making performance to drop cause a tween done in an Update loop, also a Sroty prefab was not updated with new scripts, while leaving an unused script there.

Closes #55

### CODE REVIEW

File: Where_Is_My_Wife/Assets/_Main/Scripts/Player/Cinemachine/PlayerCameraFollowComponent.cs
Comment (FerchusGames) [inline Where_Is_My_Wife/Assets/_Main/Scripts/Player/Cinemachine/PlayerCameraFollowComponent.cs:1]: I understand that we need to prevent DOTween from overloading, that was my bad, but, because we are killing the tween each frame, the rotation will become a linear interpolation, completely disregarding the plugin's eases. 

We need to find a way to fix this problem without killing the tween each frame and respecting the ease.

File: Where_Is_My_Wife/Assets/_Main/Scripts/UI/Settings/SettingSelection.cs
Comment (FerchusGames) [inline Where_Is_My_Wife/Assets/_Main/Scripts/UI/Settings/SettingSelection.cs:1]: Good catch. Since we are overriding the inherited functions, we no longer need to implement ISelectHandler, IDeselectHandler on this class and can delete them.

**Review by FerchusGames — CHANGES_REQUESTED** [review]
One really easy refactor and one important change to the way the vector that cinemachine uses rotates.

File: Where_Is_My_Wife/Assets/_Main/Scripts/UI/Settings/SettingSelection.cs [hunk 1]
```diff
@@ -14,13 +14,13 @@ protected virtual void Start()
...
         {
             base.OnSelect(eventData);
             SubscribeToActions();
         }
     
-        public virtual void OnDeselect(BaseEventData eventData)
+        public override void OnDeselect(BaseEventData eventData)
         {
             base.OnDeselect(eventData);
             SelectedUnsubscribeFromActions();
```
Comment (FerchusGames) [inline Where_Is_My_Wife/Assets/_Main/Scripts/UI/Settings/SettingSelection.cs:26]: Good catch. Since we are inheriting the interfaces implementation from MenuButton, we can delete them from this class.

**Review by FerchusGames — CHANGES_REQUESTED** [review]

**Review by FerchusGames — APPROVED** [review]
Nonsense? Okay
